# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "rmf"
title_separator          : "•"
subtitle                 : "Code, Photography, Design"
name                     : "Roy Francis"
author                   : "Roy Francis"
description              : "Code, Photography, Design"
url                      : "https://royfrancis.com" # http://127.0.0.1:4000
baseurl                  : #"/royfrancis.github.io"
repository               : #"royfrancis/royfrancis.github.io"
teaser                   : # "/assets/images/featured.jpg"
assets                   : "/assets/"
images                   : "/assets/images/"
image                    : "/assets/images/featured.jpg"
logo                     : "assets/images/android-chrome-192x192.png"
favicon:
  - rel: "apple-touch-icon"
    type: "image/png"
    size: "180x180"
    href: "/assets/images/apple-touch-icon.png"
  - rel: "icon"
    type: "image/png"
    size: "48x48"
    href: "/assets/images/favicon-48x48.png"
  - rel: "icon"
    type: "image/png"
    size: "32x32"
    href: "/assets/images/favicon-32x32.png"
  - rel: "icon"
    type: "image/png"
    size: "16x16"
    href: "/assets/images/favicon-16x16.png"
  - rel: "shortcut icon"
    href: "/assets/images/favicon.ico"
  - rel: "manifest"
    href: "/assets/images/site.webmanifest"
  - rel: "mask-icon"
    href: "/assets/images/safari-pinned-tab.svg"
    color: "#5bbad5"
custom-javascript-list:
  - "/assets/js/simplelightbox.js"
  - "/assets/js/code-copy.js"
custom-css-list:
  - "/assets/css/simplelightbox.css"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
#breadcrumbs              : # true # false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" #"discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "romf"
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true
search_full_content      : true
search_provider          : "lunr" # algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : "google-site-verification=gVz_q-4FyIIzjgUOs8-zItaFtLDCqCLhiHAAfkGb808"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-66208341-1"
    anonymize_ip         : true # true, false (default)


# Site Author
author:
  name             : "Roy Francis"
  avatar           : "assets/images/android-chrome-192x192.png"
  bio              : "Bioinformatician"
  location         :
  email            :
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://royfrancis.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RoyMFrancis"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/roy-francis/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/royfrancis"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/1310511/rmf"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Roy-Francis-2"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mindlessgreen"
    - label: "500px"
      icon: "fab fa-fw fa-500px"
      url: "https://500px.com/p/RMFP"
    - label: Feed
      icon: "fas fa-rss"
      url: "http://www.royfrancis.com/feed.xml"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - README.md
  - tmp
  - vscode.code-workspace
  - minimal-mistakes-jekyll.gemspec
  - "*.Rmd"
  - "*.R"
  - ".Rhistory"
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: :slug/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Stockholm"
destination: docs

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      is_post: true
      layout: single-mx
      author_profile: false
      read_time: false
      comments: true
      share: false
      related: true
      date_format: "%d-%b-%Y"
      future: true
      published: true
      sitemap: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single-mx
      author_profile: false
      is_pages: true
      sitemap: true
  - scope:
      path: "_layouts"
    values:
      author_profile: false